### ISSUE TITLE
language english?

### ISSUE THREAD

**Issue by pwFoo** [unix4you2/pcoder#7]
Is there a translation to english or other languages?

**Comment by unix4you2** [comment]
Yes.  It support 5 languages:
Spanish (my native language)
English
French
Portugués
Hindi

You only need to change de variable in config file for that 'en' for
English, 'hi' for hindi... Etc.

Regards

**Comment by unix4you2** [comment]
This is the file : mod/pcoder/inc/configuracion.php

In the last line.

to install it you only need to compress the file under your web server

**Comment by pwFoo** [comment]
Thanks @unix4you2,
is it possible to switch the language of the online demo to english (runtime)?

**Comment by unix4you2** [comment]
Hi @pwFoo 

Are you talking about http://demo.practico.org?   Because that's the demo for all the framework, not only the {P}Coder editor.  For security reasons the demo in Práctico Framework doesn't allow to save changes in the configuration...  To the config you can go using the cogs button in the top and then the first option.   Language is located at the right of the asistant.

But when you download, unzip it in a folder of your webserver and launch it the from the beginning the wizard let you choose your favorite language.

But Práctico is a full frework to build web and mobile apps witouth coding... PCoder is just an anidition.  If you want to test only pcoder then you should download only pcoder, unzip it and go to the URL where it is.

Regards.

**Comment by unix4you2** [comment]
What about a videoconference for an online demo? If you want I can show you what can do both projects.  Just add me to Hangouts using the same using.  I would show you it.
Regards.

**Comment by pwFoo** [comment]
A online pcoder (standalone?) demo with language english would be fine. 
Because I interested in self hosted web ide alternatives for my personal use.

**Comment by unix4you2** [comment]
Hi again @pwFoo

You can access a limited demo mode in this links.  Remember that for security reasons is limited to write some type of files only:

- For english:  [http://demo.pcoder.org/en/](http://demo.pcoder.org/en/)
- For spanish:  [http://demo.pcoder.org/es/](http://demo.pcoder.org/es/)
- For hindi:  [http://demo.pcoder.org/hi/](http://demo.pcoder.org/hi/)
- For portuguese:  [http://demo.pcoder.org/pt/](http://demo.pcoder.org/pt/)

{P}Coder is developed to work as an standalone cloud editor or a module for Practico Framework.  **BUT IS VERY IMPORTANT** that if your want to use it as an standalone editor the you remember to protect the folder where you uncompress it, for example, using an htaccess file to set a password or similar.

Regards.  John
